# 1. Create a 3x3x3 array with random values

In [1]:
import numpy as np

In [2]:
x = np.random.random((3,3,3))
print(x)

[[[0.54724914 0.80248609 0.36382124]
  [0.90602058 0.94786334 0.31042467]
  [0.08748941 0.10944808 0.66309284]]

 [[0.84995192 0.93102605 0.31291116]
  [0.0810335  0.81322212 0.16999961]
  [0.46569514 0.42207332 0.07453972]]

 [[0.36618758 0.84783224 0.79746468]
  [0.39512652 0.65688198 0.05577372]
  [0.56432983 0.59649595 0.95148625]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
ar = np.diag(1+np.arange(4),k=-1)
print(ar)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
A = np.zeros((8,8),dtype=int)
A[1::2,::2] = 1
A[::2,1::2] = 1
print(A)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [5]:
arr = np.random.random((5,5))
arr = (arr - np.mean (arr)) / (np.std (arr))
arr

array([[-1.04189675,  0.72565558,  1.6282933 , -0.10548711,  1.16813515],
       [ 0.49088035, -0.87884011,  0.10400014,  0.57665787, -0.92406162],
       [-1.4807405 ,  0.1471426 , -0.71705549,  0.87316376, -1.12940576],
       [-1.45946348,  1.39979681, -0.57029931, -1.40394836,  1.37841197],
       [-0.51754713, -0.22908934,  0.94779294, -0.5776505 ,  1.595555  ]])

# 5. How to find common values between two arrays?

In [14]:
A1 = np.random.randint(0,10,10)
A2 = np.random.randint(0,10,10)
print(np.intersect1d(A1,A2))

[6 7 8]


# 6.How to get the dates of yesterday, today and tomorrow?

In [15]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print("Yesterday: ",yesterday)
print("Today: ",today)
print("Tomorrow",tomorrow)

Yesterday:  2020-08-01
Today:  2020-08-02
Tomorrow 2020-08-03


# 7. Consider two random array A and B, check if they are equal

In [18]:
A = np.random.randint(0,3,4)
B = np.random.randint(0,3,4)
equal = np.allclose(A,B)
print(equal)
equal = np.array_equal(A,B)
print(equal)

False
False


# 8.Create random vector of size 10 and replace the maximum value by 0

In [19]:

X = np.random.rand(10)
X[X.argmax()] = 0
print(X)

[0.         0.8159585  0.67564805 0.61195234 0.80284572 0.75073821
 0.22056947 0.21091837 0.36530699 0.4606472 ]


# 9. How to print all the values of an array?

In [20]:
X = np.zeros((10,10))
print(X)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [23]:
X = np.random.rand(3, 3)
Y = X - X.mean(axis=1, keepdims=True)
Y1 = X - X.mean(axis=1).reshape(-1, 1)
print(Y)
print(Y1)

[[ 0.40644339 -0.18727889 -0.21916451]
 [-0.17993512  0.2092394  -0.02930428]
 [ 0.06327568 -0.03623623 -0.02703945]]
[[ 0.40644339 -0.18727889 -0.21916451]
 [-0.17993512  0.2092394  -0.02930428]
 [ 0.06327568 -0.03623623 -0.02703945]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [26]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)
np.add.at(Z, I, 1)
print(Z)

[3. 4. 4. 1. 3. 4. 2. 3. 3. 3.]
[5. 7. 7. 1. 5. 7. 3. 5. 5. 5.]


# 12.How to get the diagonal of a dot product?

In [27]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
print(A)
print(B)
prod1=np.diag(np.dot(A, B))
print("diagonal of a dot product is....",prod1)

[[0.66873671 0.66780849 0.1696537  0.60824961 0.8303355 ]
 [0.19509927 0.08263884 0.44995456 0.03727148 0.5043001 ]
 [0.05016046 0.13216234 0.29113361 0.48079456 0.98284143]
 [0.96599136 0.13539917 0.24956193 0.54138516 0.34362787]
 [0.97661983 0.99098076 0.4390431  0.42141165 0.11497597]]
[[0.11309989 0.88683901 0.29874033 0.34063155 0.61249269]
 [0.86550154 0.21062688 0.79125336 0.5460644  0.47656063]
 [0.25859737 0.02726751 0.07700951 0.26857143 0.40928123]
 [0.52048459 0.78680601 0.81587296 0.31764437 0.54383984]
 [0.52072308 0.16458612 0.36048047 0.71133162 0.65041106]]
diagonal of a dot product is.... [1.44645473 0.31502297 0.88854133 0.88641033 1.55408911]


# 13.How to find the most frequent value in an array?

In [28]:
C = np.random.randint(0,10,30)
print(C)
print(np.bincount(C).argmax())

[1 1 8 6 3 3 9 2 4 3 2 5 9 8 5 9 0 2 5 7 4 4 2 0 7 1 9 6 6 4]
2


# 14.How to get the n largest values of an array

In [29]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


# 15.How to create a record array from a regular array?

In [31]:
Z = np.array([("Hello", 2.8, 4),
              ("World", 3.9, 6)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.8, 4) (b'World', 3.9, 6)]
